# Generated by Django 5.0.6 on 2024-05-18 12:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
