# Generated by Django 5.0.6 on 2024-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelic', '0003_tourpackage_delete_tourpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
