# Generated by Django 5.0.6 on 2024-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelic', '0004_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
